### ISSUE TITLE
An error occurred while installing the Python dependenlcies for local-music-skill

### ISSUE THREAD

**Issue by GoldenbyteGH** [thevirtuoso1973/local-music-skill#1]
ERROR: Could not find a version that satisfies the requirement os (from versions: none)

**Comment by thevirtuoso1973** [comment]
Looks like an issue with the manifest, removing `os` and/or `random` may fix this. PRs are welcome.

https://github.com/thevirtuoso1973/local-music-skill/blob/998bfde802a27a3120276bc7b141fcc54ffe2d11/manifest.yml#L3-L5

**Comment by JohnMcLear** [comment]
Confirmed bug.

**Comment by senkumartup** [comment]
No luck


 (.venv) pi@picroft:~/t/local-music-skill$ git diff
 diff --git a/manifest.yml b/manifest.yml
 index 762a15d..12c1195 100644
 --- a/manifest.yml
 +++ b/manifest.yml
 @@ -1,8 +1,6 @@
   dependencies:
     # Pip dependencies on PyPI
     python:
  -     - os
  -     - random
 
     skills:
       - mycroft-playback-control

(.venv) pi@picroft:~/t$ mycroft-msm install local-music-skill/
INFO - building SkillEntry objects for all skills
INFO - Best match (0.24): skill-crystal-ball by Arc676
SkillNotFound: local-music-skill/

**Comment by senkumartup** [comment]
(.venv) pi@picroft:~/t/local-music-skill$ git diff
 diff --git a/manifest.yml b/manifest.yml
 index 762a15d..12c1195 100644
 --- a/manifest.yml
 +++ b/manifest.yml
 @@ -1,8 +1,6 @@
   dependencies:
     # Pip dependencies on PyPI
     python:
  -     - os
  -     - random
 
     skills:
       - mycroft-playback-control

**Comment by senkumartup** [comment]
Fix

https://github.com/senkumartup/local-music-skill

**Comment by thevirtuoso1973** [comment]
>(.venv) pi@picroft:~/t$ mycroft-msm install local-music-skill/
INFO - building SkillEntry objects for all skills
INFO - Best match (0.24): skill-crystal-ball by Arc676
SkillNotFound: local-music-skill/

@senkumartup 
Try installing like this https://mycroft-ai.gitbook.io/docs/skill-development/mycroft-skills-manager#from-a-github-repository? This skill probably isn't in the marketplace.
